package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.C3791c;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

public final class bf<R extends Result> extends C3791c<R> {
    /* renamed from: a */
    private final BasePendingResult<R> f13972a;

    public bf(PendingResult<R> pendingResult) {
        if (pendingResult instanceof BasePendingResult) {
            this.f13972a = (BasePendingResult) pendingResult;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    /* renamed from: a */
    public final R mo2484a(long j, TimeUnit timeUnit) {
        return this.f13972a.mo2484a(j, timeUnit);
    }

    /* renamed from: a */
    public final void mo2485a() {
        this.f13972a.mo2485a();
    }

    /* renamed from: a */
    public final void mo2486a(zza zza) {
        this.f13972a.mo2486a(zza);
    }

    /* renamed from: a */
    public final void mo2487a(ResultCallback<? super R> resultCallback) {
        this.f13972a.mo2487a((ResultCallback) resultCallback);
    }

    /* renamed from: b */
    public final boolean mo2488b() {
        return this.f13972a.mo2488b();
    }

    /* renamed from: c */
    public final Integer mo2489c() {
        return this.f13972a.mo2489c();
    }
}
